# Generated by Django 5.1.5 on 2025-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='reward_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
