# Generated by Django 5.1.3 on 2025-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('booking_date', models.CharField(blank=True, max_length=15, null=True)),
                ('booking_time', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
