# Generated by Django 5.1.5 on 2025-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.TextField(max_length=255),
        ),
    ]
