# Generated by Django 5.1.5 on 2025-02-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('leave', 'Xin nghỉ'), ('working', 'Đang trong ca'), ('off', 'Tan ca')], default='working', max_length=10)),
            ],
        ),
    ]
