# Generated by Django 5.1.5 on 2025-02-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('leave', 'Xin nghỉ'), ('working', 'Đang trong ca'), ('on_leave', 'Đang nghỉ phép'), ('off', 'Tan ca')], default='working', max_length=10),
        ),
    ]
