# Generated by Django 5.1.5 on 2025-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('off', 'Xin nghỉ'), ('working', 'Đang làm'), ('on_leave', 'Đang nghỉ phép')], default='working', max_length=10),
        ),
    ]
